[project]
name = "de-learner"
version = "0.0.1"
description = "This is a template repository for Python projects that use uv for their dependency management."
authors = [
  { name = "miloKmilo", email = "campero189@gmail.com" },
]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.12,<4.0"
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "loguru>=0.7.3",
    "mypy>=1.17.0",
    "pandas>=2.3.1",
    "pandas-stubs>=2.3.0.250703",
    "pgcli>=4.3.0",
    "psycopg2-binary>=2.9.10",
    "pyarrow>=21.0.0",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
    "tenacity>=9.1.2",
    "types-requests>=2.32.4.20250611",
]

[project.urls]
Homepage = "https://miloKmilion.github.io/de-learner/"
Repository = "https://github.com/miloKmilion/de-learner"
Documentation = "https://miloKmilion.github.io/de-learner/"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pre-commit>=4.1.0",
    "tox-uv>=1.25.0",
    "deptry>=0.23.0",
    "mypy>=1.15.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.9.10",
    "mkdocs>=1.4.2",
    "mkdocs-material>=9.6.7",
    "mkdocs-github-admonitions-plugin>=0.0.3",
    "mkdocstrings[python]>=0.29.0",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["de_learner"]

[tool.mypy]
files = ["de_learner"]
exclude = [
    "de_learner/module_01/1_terraform",
    "de_learner/module_01/2_docker_sql",
]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
ignore_missing_imports = true


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py312"
line-length = 120
fix = true


[tool.ruff.lint]
select = [
  # flake8-2020
  "YTT",
  # flake8-bandit
  "S",
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-comprehensions
  "C4",
  # flake8-debugger
  "T10",
  # flake8-simplify
  "SIM",
  # isort
  "I",
  # mccabe
  "C90",
  # pycodestyle
  "E",
  "W",
  # pyflakes
  "F",
  # pygrep-hooks
  "PGH",
  # pyupgrade
  "UP",
  # ruff
  "RUF",
  # tryceratops
  "TRY",
  # Pylint-equivalent rules
  "PLC",
  "PLE",
  "PLR",
  "PLW",
]
ignore = [
  # LineTooLong
  "E501",
  # DoNotAssignLambda
  "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]


preview = true
[tool.coverage.report]
skip_empty = true

[tool.coverage.run]


branch = true
source = ["de_learner"]

[tool.deptry]
extend_exclude = ["de_learner/module_01"]
ignore = ["DEP002"]  # Ignore dependencies defined but not used (educational examples)
